---
- hosts: webservers
  become: true
  gather_facts: true
  vars:
      user: admin
      passwd: Mgr@1998 
  tasks:
    - name: upload file to Nexus
      uri:
       url: " http://{{ nexus_ip }}:8081/repository/gow-maven/"
       validate_certs: no
       method: "PUT"
       status_code: 201, 200, 500, 400, 401
       url_username: "{{ user }}"
       url_password: "{{ passwd }}"
...

